fme ..\FME\BAG_INSPIRE_ADR_ADR.fmw  --LOG_FILE      "..\log\BAG_INSPIRE_ADR_ADR.log"    --MAX_FEATURES  10

fme ..\FME\BAG_INSPIRE_ADR_PDC.fmw  --LOG_FILE      "..\log\BAG_INSPIRE_ADR_PDC.log"    --MAX_FEATURES  10

fme ..\FME\BAG_INSPIRE_ADR_TFN.fmw  --LOG_FILE      "..\log\BAG_INSPIRE_ADR_TFN.log"    --MAX_FEATURES  10

fme ..\FME\BAG_INSPIRE_ADR_AA.fmw   --LOG_FILE      "..\log\BAG_INSPIRE_ADR_AA.log"     --MAX_FEATURES  10


